#!/usr/bin/python -B

import sys
import os
import ConfigParser
import argparse
import boto3
import json
import multiprocessing
import time

import core.logger as log
import messaging.rmq as rmq
import vehicle.rover as rover

# Setup input arguments
arg_parser = argparse.ArgumentParser(description='Usage options for aws_init')
arg_parser.add_argument('-c', '--configfile', help="Optional - configuration file path")
arg_parser.add_argument('-l', '--logfile', help="Optional - Log file path")
arg_parser.add_argument('-i', '--keyid', help="AWS access key ID ")
arg_parser.add_argument('-k', '--key', help="AWS access key")
arg_parser.add_argument('-v', '--vehicleid', help="Optional - override default vehicle ID")


# Process input and generate dict
args = vars(arg_parser.parse_args())


# Validate input - Config file
if args['configfile'] is not None:
    configfilepath = args['configfile']
else:
    local_path = os.path.dirname(os.path.abspath(__file__))
    configfilepath = str(local_path) + '/config/sqs_adaptor.cfg'

# Get config
try:
    assert os.path.isfile(configfilepath), "Error: Config file does not exist"

    config = ConfigParser.ConfigParser()
    config.read(configfilepath)
except:
    raise SystemExit("FATAL: Unknown error 001 - " + str(sys.exc_info()[0]))


# Validate input - Log file
if args['logfile'] is not None:
    logfilepath = args['logfile']
else:
    logfilepath = config.get('logging', 'path')    

# Setup logging
try:
    logfile = log.CreateLogger(toconsole=False, tofile=True, filepath=logfilepath, level=config.get('logging', 'level'))
    assert logfile, "Error: Failed to create log outputs"

except:
    raise SystemExit("FATAL: Unknown error 002 - " + str(sys.exc_info()[0]))


# Validate input - access creds
if args['keyid'] is None: 
    raise SystemExit("Error: No key id provided")
else:
    AWS_KEY_ID = args['keyid']

if args['key'] is None: 
    raise SystemExit("Error: No key provided")
else:
    AWS_KEY = args['key']


# Validate input - vehicle id
if args['vehicleid'] is not None:
    RMQ_TOPIC = args['vehicleid']
else:
    RMQ_TOPIC = config.get('platform_broker', 'unit_id')


# Validate config
try:
    AWS_DEFAULT_REGION = config.get('aws_defaults', 'region')
    AWS_DEFAULT_QUEUE_NAME = config.get('aws_defaults', 'queue_name')

    RMQ_HOST_CONTROL = config.get('platform_broker', 'control_server')
    RMQ_PORT_CONTROL = int(config.get('platform_broker', 'control_port'))
    RMQ_EXCHANGE_CONTROL = config.get('platform_broker', 'control_exchange')

    RMQ_HOST_VEHICLE = config.get('platform_broker', 'vehicle_server')
    RMQ_PORT_VEHICLE = int(config.get('platform_broker', 'vehicle_port'))
    RMQ_EXCHANGE_VEHICLE = config.get('platform_broker', 'vehicle_exchange')


    logfile.debug("Configuration file loaded")

except ConfigParser.NoSectionError as err:
    logfile.error("Error: " + str(err))
    raise SystemExit("Error: " + str(err))

except ConfigParser.NoOptionError as err:
    logfile.error("Error: " + str(err))
    raise SystemExit("Error: " + str(err))

except:
    raise SystemExit("FATAL: Unknown error 003 - " + str(sys.exc_info()[0]))

# Global vars
VEHICLE_DATA = rover.piRoverVehicle()
CONTROL_DATA = rover.piRoverControls()

def processRMQInput(data):
# Populate global var from RMQ JSON messages
    logfile.debug("Received data from RMQ: " + str(data))
    try:
        json_data = json.loads(data)

        # NON RETURNING (ingest only)
        if 'camera' in json_data:
            if 'tilt' in json_data['camera']: CONTROL_DATA.cameraTiltPosition = json_data['camera']['tilt']
            if 'pan' in json_data['camera']: CONTROL_DATA.cameraPanPosition = json_data['camera']['pan']
            if 'light' in json_data['camera']: CONTROL_DATA.cameraLightState = json_data['camera']['light']

        if 'vehicle' in json_data:
            if 'throttle' in json_data['vehicle']: CONTROL_DATA.throttlePosition = json_data['vehicle']['throttle']
            if 'direction' in json_data['vehicle']: CONTROL_DATA.directionPosition = json_data['vehicle']['direction']
            if 'brake' in json_data['vehicle']: CONTROL_DATA.brakeState = json_data['vehicle']['brake']
            if 'light' in json_data['vehicle']: CONTROL_DATA.vehicleLightState = json_data['vehicle']['light']
            if 'wifi' in json_data['vehicle']: VEHICLE_DATA.vehicleWifi = json_data['vehicle']['wifi']
            if 'batteryA' in json_data['vehicle']: VEHICLE_DATA.vehicleBatteryA = json_data['vehicle']['batteryA']
            if 'batteryB' in json_data['vehicle']: VEHICLE_DATA.vehicleBatteryB = json_data['vehicle']['batteryB']

        if 'environment' in json_data:
            if 'temperature' in json_data['environment']: VEHICLE_DATA.environmentTemperature = json_data['environment']['temperature']
            if 'humidity' in json_data['environment']: VEHICLE_DATA.environmentHumidity = json_data['environment']['humidity']
            if 'pressure' in json_data['environment']: VEHICLE_DATA.environmentPressure = json_data['environment']['pressure']

        if 'GPS' in json_data:
            if 'latitude' in json_data['GPS']: VEHICLE_DATA.gpsLatitude = json_data['GPS']['latitude']
            if 'longitude' in json_data['GPS']: VEHICLE_DATA.gpsLongitude = json_data['GPS']['longitude']
            if 'speed' in json_data['GPS']: VEHICLE_DATA.gpsSpeed = json_data['GPS']['speed']
            if 'altitude' in json_data['GPS']: VEHICLE_DATA.gpsAltitude = json_data['GPS']['altitude']

        if 'accelerometer' in json_data:
            if 'x' in json_data['accelerometer']: VEHICLE_DATA.accelLR = json_data['accelerometer']['x']
            if 'y' in json_data['accelerometer']: VEHICLE_DATA.accelRF = json_data['accelerometer']['y']

        return(True)

    except:
        return(False)


def postSQSMessage(queue):
# Post data from globals to SQS
    try:
        post_data = {'latitude': VEHICLE_DATA.gpsLatitude, 
                     'longitude': VEHICLE_DATA.gpsLongitude,
                     'altitude': VEHICLE_DATA.gpsAltitude,
                     'throttle': CONTROL_DATA.throttlePosition,
                     'direction': CONTROL_DATA.directionPosition}

        queue.send_message(QueueUrl=queue.url, 
                           MessageBody=json.dumps(post_data), 
                           MessageAttributes={'vehicle_id': {'StringValue':RMQ_TOPIC, 'DataType':'String'}})

        logfile.debug("Posted message to SQS")
        return True

    except:
        return False



def main():
    #### Connect to AWS resources
    try:
        session = boto3.session.Session(aws_access_key_id=AWS_KEY_ID, aws_secret_access_key=AWS_KEY, region_name=AWS_DEFAULT_REGION)
        logfile.info("Connected to AWS")

    except:
        assert False, "Error: Could not connect to AWS"

    sqs_client = session.client('sqs')
    queue_url = sqs_client.get_queue_url(QueueName=AWS_DEFAULT_QUEUE_NAME)['QueueUrl']

    sqs = session.resource('sqs')
    sqs_queue = sqs.Queue(queue_url)


    #### SETUP RABBITMQ CONNECTIONS
    ## Control
    # Reader
    rmq_control_pconn, rmq_control_cconn = multiprocessing.Pipe()
    rmq_control_reader = rmq.rmqClientReader(host=RMQ_HOST_CONTROL, port=RMQ_PORT_CONTROL, log=logfile)

    if rmq_control_reader.connected == False:
        raise SystemExit("FATAL: Failed to connect to RQM broker")
    logfile.info("Connected to RMQ server - control")

    rmq_control_reader.subscribe(RMQ_EXCHANGE_CONTROL, RMQ_TOPIC)
    logfile.info("Subscribed to RMQ control topic " + RMQ_TOPIC)

    rmq_control_thread = multiprocessing.Process(target=rmq_control_reader.run, args=(rmq_control_cconn,))
    rmq_control_thread.daemon = True
    rmq_control_thread.start()

    ## Vehicle
    # Reader
    rmq_vehicle_pconn, rmq_vehicle_cconn = multiprocessing.Pipe()
    rmq_vehicle_reader = rmq.rmqClientReader(host=RMQ_HOST_VEHICLE, port=RMQ_PORT_VEHICLE)

    if rmq_vehicle_reader.connected == False:
        raise SystemExit("FATAL: Failed to connect to RQM broker")
    logfile.info("Connected to RMQ server - vehicle")
 
    rmq_vehicle_reader.subscribe(RMQ_EXCHANGE_VEHICLE, RMQ_TOPIC)
    logfile.info("Subscribed to RMQ vehicle topic " + RMQ_TOPIC)

    rmq_vehicle_thread = multiprocessing.Process(target=rmq_vehicle_reader.run, args=(rmq_vehicle_cconn,))
    rmq_vehicle_thread.daemon = True
    rmq_vehicle_thread.start()


    # Forever loop
    counter = 0
    while 1:
 
        # ~10s subloop
        if counter == 100:
            counter = 0
            result = postSQSMessage(queue=sqs_queue)
            assert result, "Error: Failed posting vehicle data"
          
        # Control data
        if rmq_control_pconn.poll() == True: 
            logfile.debug("Recieved data from RMQ - control")
            result = processRMQInput(rmq_control_pconn.recv())
            assert result, "Error: Failed processing RMQ control data"
            
        # Vehicle data
        if rmq_vehicle_pconn.poll() == True: 
            logfile.debug("Recieved data from RMQ - vehicle")
            result = processRMQInput(rmq_vehicle_pconn.recv())
            assert result, "Error: Failed processing RMQ control data"

        counter += 1
        time.sleep(.1)


if __name__ == '__main__':
    try: 
        main()
    except (KeyboardInterrupt, SystemExit) as err:
        logfile.info("User action - Exiting")
        print str(err) + " -- Exiting..."

    except AssertionError as err:
        print str(err)

    except:
        print "Error: unknown error 000 - " + str(sys.exc_info()[0])
