#!/usr/bin/python -B

import json
import time
import multiprocessing
import ConfigParser
import argparse
import sys
import os.path
import pycurl

from StringIO import StringIO

import class_rover as rover
import class_rmq as rmq
import func_logging as log


# Setup input arguments
arg_parser = argparse.ArgumentParser(description='Usage options for edgware adaptor')
arg_parser.add_argument('-c', '--configfile', help="Optional - configuration file path")
arg_parser.add_argument('-l', '--logfile', help="Optional - Log file path")
# Process input and generate dict
args = vars(arg_parser.parse_args())


# Validate input - Config file
if args['configfile'] is not None:
    configfilepath = args['configfile']
else:
    configfilepath = 'data-poster.cfg'

if not os.path.isfile(configfilepath): 
   raise SystemExit("ERROR: File not found - " + str(configfilepath))

# Get config
try:
    config = ConfigParser.ConfigParser()
    config.read(configfilepath)
except:
    raise SystemExit("FATAL: Unknown error - " + str(sys.exc_info()[0]))

# Validate input - Log file
if args['logfile'] is not None:
    logfilepath = args['logfile']
else:
    logfilepath = config.get('logging', 'path')

# Setup logging
try:
    logfile = log.CreateLogger(toconsole=False, tofile=True, filepath=logfilepath, level=config.get('logging', 'level'))
    assert logfile, "Error: Failed to create log outputs"

except:
    raise SystemExit("FATAL: Unknown error - " + str(sys.exc_info()[0]))


# Parse config data, convert to vars
try:
    # RabbitMQ connection details
    RMQ_TOPIC = config.get('platform_broker', 'unit_id')

    RMQ_HOST_CONTROL = config.get('platform_broker', 'control_server')
    RMQ_PORT_CONTROL = int(config.get('platform_broker', 'control_port'))
    RMQ_EXCHANGE_CONTROL = config.get('platform_broker', 'control_exchange')

    RMQ_HOST_VEHICLE = config.get('platform_broker', 'vehicle_server')
    RMQ_PORT_VEHICLE = int(config.get('platform_broker', 'vehicle_port'))
    RMQ_EXCHANGE_VEHICLE = config.get('platform_broker', 'vehicle_exchange')

    API_URL = config.get('API', 'url')
    API_PORT = int(config.get('API', 'port'))

except ConfigParser.NoSectionError as err:
    raise SystemExit("Error: " + str(err))

except ConfigParser.NoOptionError as err:
    raise SystemExit("Error: " + str(err))

except:
    raise SystemExit("FATAL: Unknown error - " + str(sys.exc_info()[0]))

# Global vars
VEHICLE_DATA = rover.piRoverVehicle()
CONTROL_DATA = rover.piRoverControls()

def processRMQInput(data):
# Populate global var from RMQ JSON messages
    logfile.debug("Received data from RMQ: " + str(data))
    try:
        json_data = json.loads(data)

        # NON RETURNING (ingest only)
        if 'camera' in json_data:
            if 'tilt' in json_data['camera']: CONTROL_DATA.cameraTiltPosition = json_data['camera']['tilt']
            if 'pan' in json_data['camera']: CONTROL_DATA.cameraPanPosition = json_data['camera']['pan']
            if 'light' in json_data['camera']: CONTROL_DATA.cameraLightState = json_data['camera']['light']

        if 'vehicle' in json_data:
            if 'throttle' in json_data['vehicle']: CONTROL_DATA.throttlePosition = json_data['vehicle']['throttle']
            if 'direction' in json_data['vehicle']: CONTROL_DATA.directionPosition = json_data['vehicle']['direction']
            if 'brake' in json_data['vehicle']: CONTROL_DATA.brakeState = json_data['vehicle']['brake']
            if 'light' in json_data['vehicle']: CONTROL_DATA.vehicleLightState = json_data['vehicle']['light']
            if 'wifi' in json_data['vehicle']: VEHICLE_DATA.vehicleWifi = json_data['vehicle']['wifi']
            if 'batteryA' in json_data['vehicle']: VEHICLE_DATA.vehicleBatteryA = json_data['vehicle']['batteryA']
            if 'batteryB' in json_data['vehicle']: VEHICLE_DATA.vehicleBatteryB = json_data['vehicle']['batteryB']

        if 'environment' in json_data:
            if 'temperature' in json_data['environment']: VEHICLE_DATA.environmentTemperature = json_data['environment']['temperature']
            if 'humidity' in json_data['environment']: VEHICLE_DATA.environmentHumidity = json_data['environment']['humidity']
            if 'pressure' in json_data['environment']: VEHICLE_DATA.environmentPressure = json_data['environment']['pressure']

        if 'GPS' in json_data:
            if 'latitude' in json_data['GPS']: VEHICLE_DATA.gpsLatitude = json_data['GPS']['latitude']
            if 'longitude' in json_data['GPS']: VEHICLE_DATA.gpsLongitude = json_data['GPS']['longitude']
            if 'speed' in json_data['GPS']: VEHICLE_DATA.gpsSpeed = json_data['GPS']['speed']
            if 'altitude' in json_data['GPS']: VEHICLE_DATA.gpsAltitude = json_data['GPS']['altitude']

        if 'accelerometer' in json_data:
            if 'x' in json_data['accelerometer']: VEHICLE_DATA.accelLR = json_data['accelerometer']['x']
            if 'y' in json_data['accelerometer']: VEHICLE_DATA.accelRF = json_data['accelerometer']['y']

        return(True)

    except:
        return(False)


def writeHTTPOutput():
#    try:
        post_data = {}
        post_data['vehicle_id'] = RMQ_TOPIC
        post_data['vehicle_data'] = {'latitude': VEHICLE_DATA.gpsLatitude, 
                                     'longitude': VEHICLE_DATA.gpsLongitude,
                                     'altitude': VEHICLE_DATA.gpsAltitude,
                                     'throttle': CONTROL_DATA.throttlePosition,
                                     'direction': CONTROL_DATA.directionPosition}

        buffer = StringIO()

        c = pycurl.Curl()
        c.setopt(c.URL, API_URL)
        c.setopt(c.PORT, API_PORT)
        c.setopt(c.WRITEDATA, buffer)
        c.setopt(c.POSTFIELDS, json.dumps(post_data))
        c.perform()

        response = buffer.getvalue()
        print response
        return(response)

#    except:
#        return(False)



def main():
    #### SETUP RABBITMQ CONNECTIONS
    ## Control
    # Reader
    rmq_control_pconn, rmq_control_cconn = multiprocessing.Pipe()
    rmq_control_reader = rmq.rmqClientReader(host=RMQ_HOST_CONTROL, port=RMQ_PORT_CONTROL, log=logfile)

    if rmq_control_reader.connected == False:
        raise SystemExit("FATAL: Failed to connect to RQM broker")
    logfile.info("Connected to RMQ server - control")

    rmq_control_reader.subscribe(RMQ_EXCHANGE_CONTROL, RMQ_TOPIC)
    logfile.info("Subscribed to RMQ control topic " + RMQ_TOPIC)

    rmq_control_thread = multiprocessing.Process(target=rmq_control_reader.run, args=(rmq_control_cconn,))
    rmq_control_thread.daemon = True
    rmq_control_thread.start()

    ## Vehicle
    # Reader
    rmq_vehicle_pconn, rmq_vehicle_cconn = multiprocessing.Pipe()
    rmq_vehicle_reader = rmq.rmqClientReader(host=RMQ_HOST_VEHICLE, port=RMQ_PORT_VEHICLE)

    if rmq_vehicle_reader.connected == False:
        raise SystemExit("FATAL: Failed to connect to RQM broker")
    logfile.info("Connected to RMQ server - vehicle")
 
    rmq_vehicle_reader.subscribe(RMQ_EXCHANGE_VEHICLE, RMQ_TOPIC)
    logfile.info("Subscribed to RMQ vehicle topic " + RMQ_TOPIC)

    rmq_vehicle_thread = multiprocessing.Process(target=rmq_vehicle_reader.run, args=(rmq_vehicle_cconn,))
    rmq_vehicle_thread.daemon = True
    rmq_vehicle_thread.start()


    # Forever loop
    counter = 0



    while 1:
 
        # ~10s subloop
        if counter == 100:
            counter = 0
            result = writeHTTPOutput()
            assert result, "Error: Failed posting vehicle data"
          

        if rmq_control_pconn.poll() == True: 
            logfile.debug("Recieved data from RMQ - control")
            result = processRMQInput(rmq_control_pconn.recv())
            assert result, "Error: Failed processing RMQ control data"
            

        if rmq_vehicle_pconn.poll() == True: 
            logfile.debug("Recieved data from RMQ - vehicle")
            result = processRMQInput(rmq_vehicle_pconn.recv())
            assert result, "Error: Failed processing RMQ control data"


        counter += 1
        time.sleep(.1)

    # Clean-up
    rmq_control_thread.join()
    rmq_vehicle_thread.join()



if __name__ == '__main__':
#    try: 
        main()
#    except (KeyboardInterrupt, SystemExit) as err:
#        logfile.info("User action - Exiting")
#        print str(err) + " -- Exiting..."

#    except AssertionError as err:
#        print str(err)

#    except:
#        print "Error: unknown error - " + str(sys.exc_info()[0])

