#!/usr/bin/python -B
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer 

import class_handlers as handlers 


def _start_server(port=80):
    server_address = ('', port)

    httpd = HTTPServer(server_address, handlers.http_handler)

    print 'Starting httpd...'
    httpd.serve_forever() 


if __name__ == "__main__":
    from sys import argv
    if len(argv) == 2:
        _start_server(int(argv[1]))
    else:
       _start_server()
