#!/usr/bin/python -B

import wx
import sys

import controls_gui as gui

def load_window():
	# Setup wx.Python 'app' and apply 'gui' class
        app=wx.PySimpleApp()
        frame=gui.MainWindow(parent=None,id=-1)
        frame.Show()
        app.MainLoop()


load_window()

